### ISSUE TITLE
Cannot toggle S rank spawn announcement

### ISSUE THREAD

**Issue by SoftPraise** [NadyaNayme/TidyChat#89] opened 2024-11-28 22:38 UTC
Regardless of what is checked/unchecked, I cannot get the S Rank Hunt spawn message to appear in the chat log, unless I turn off `Filter System channel` altogether.
I've tried toggling the `Show S Rank Hunt spawn announcement` setting on and off, and regardless of what I do, I get `[TidyChat] [System] [Blocked] [ShowSRankHunt] You sense the presence of a powerful mark...` in Dry Run Mode. I've also tried whitelisting `sense` in the custom filters, but still nothing.
SS rank notifications, on the other hand, do appear, logging `[TidyChat] [System] [Allowed] [ShowSSRankHunt] The minions of an extraordinarily powerful mark are on the hunt for prey...` in Dry Run Mode.

**Comment by Error-Error-Error** [comment] 2024-11-28 22:57
The same is affecting the Show Experience Gain messages. No matter the toggle, it is blocked, as per Dry Run Mode messages.

**Comment by TrueWolfs** [comment] 2024-11-29 19:54
> this is also affecting custom emotes (`/em`) regardless of the toggles, they are blocked as per Dry Run mode

I'm having the same issue. Can't get ('/em') to appear.

**Comment by NadyaNayme** [comment] 2024-11-30 00:54
Emotes should be fixed as of 2.0.8. I forgot to fix the experience - as the issue is the regex checks for "gains" instead of "gain".

I'll look into why S rank is broken. Especially since SS rank works and neither regex was adjusted for 2.0. Not exactly sure what it isnt matching.

**Comment by NadyaNayme** [comment] 2024-11-30 02:13
This will be fixed in 2.0.10 as well as the Show Experience Gain message.

It will probably be on Monday as I need to resolve a framerate issue (#92) and I'm not sure if I'll be able to investigate that issue sooner.

**Closed by NadyaNayme** 2024-11-30 02:13 UTC
