### ISSUE TITLE
[BUG] Assigning retainers to gather Sideritis Leaves doesn't get filtered in chat.

### ISSUE THREAD

**Issue by Xiniox** [NadyaNayme/TidyChat#81] opened 2024-02-08 22:53 UTC
When you assign a retainer to gather Sideritis Leaves, the message "**You assign your retainer "Lv. 88 Sideritis Leaves."** " still shows up, even though it should be filtered.
![image](https://github.com/NadyaNayme/TidyChat/assets/33554580/3569cad8-d5b6-4ff7-8d9e-3694a9bcd28d)

**Comment by NadyaNayme** [comment] 2024-07-11 19:25
That is an interesting one. I can't even find what whitelist Regex this is even matching.

"assign" isn't in any filters. "retainer" isn't in any filters. "side/sideritis" aren't in any filters. "leaves" is partially in "goldleaves" for tribal quest currencies but that wouldn't match on "Leaves" since I'm searching for the full "goldleaves" and not 'contains "leves"'.

I never saw this when it was more timely to fix - so my apologies. But also I'm not even sure what whitelist filter this is hitting to be shown.

Do you have any custom filters setup by any chance? Wondering if perhaps you're tripping one of your own filters.

**Comment by NadyaNayme** [comment] 2024-07-23 06:10
I am unable to replicate this in Tidy Chat 2.0. I'm going to close this issue as I am fairly certain it is caused by one of the user's custom filters.

**Closed by NadyaNayme** 2024-07-23 06:10 UTC
Labels: whitelist-request
